export class BridgeError extends Error {
  constructor(
    public readonly code: string,
    message?: string,
  ) {
    super(message ?? code);
    this.name = "BridgeError";
  }
}

export const ErrorCodes = {
  WORKER_COMMITTED: "WORKER_COMMITTED",
  WORKER_REQUIRED: "WORKER_REQUIRED",
  WORKER_NOT_ALLOWED: "WORKER_NOT_ALLOWED",
  REVIEW_DIGEST_MISSING: "REVIEW_DIGEST_MISSING",
  REVIEW_DRIFT: "REVIEW_DRIFT",
  TARGET_REPO_BUSY: "TARGET_REPO_BUSY",
  TARGET_BRANCH_CHANGED: "TARGET_BRANCH_CHANGED",
  TARGET_HEAD_CHANGED: "TARGET_HEAD_CHANGED",
  TARGET_DIRTY: "TARGET_DIRTY",
  VERIFICATION_PLAN_MISSING: "VERIFICATION_PLAN_MISSING",
  VERIFICATION_PLAN_INVALID: "VERIFICATION_PLAN_INVALID",
  PATH_ESCAPE: "PATH_ESCAPE",
  GITLINK_NOT_SUPPORTED: "GITLINK_NOT_SUPPORTED",
  IN_PLACE_NOT_ALLOWED: "IN_PLACE_NOT_ALLOWED",
  APPLY_CONFLICT: "APPLY_CONFLICT",
} as const;
